
/*
#include "PersonneException.h"

namespace tp
{
 using namespace std;
 PersonneException::PersonneException(const string& raison)
 : std::runtime_error(raison)
 {
 };
}
*/
